[package]
name = "rc-clipboard"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Windows clipboard text get/set + change watching."

[lib]
name = "rc_clipboard"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
tracing.workspace = true

[dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_System_DataExchange",
    "Win32_System_Memory",
    "Win32_System_Ole",
]
